name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish SQLite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate SQLite DB
      run: ./ci.sh
    - name: Cache libretrodb_tool
      uses: actions/cache@v3
      with:
        path: >
          libretrodb_tool
          libretro-database
        key: ${{ runner.os }}-${{ hashFiles('libretrodb_tool') }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libretro-db.sqlite
        asset_name: libretro-${{ github.ref }}.sqlite
        tag: ${{ github.ref }}
        overwrite: true
